export const ENABLE_ADD_SUBJECT_LOADER = 'ENABLE_ADD_SUBJECT_LOADER';
export const DISABLE_ADD_SUBJECT_LOADER = 'DISABLE_ADD_SUBJECT_LOADER';

export const ADD_SUBJECT_REQUEST = 'ADD_SUBJECT_REQUEST';
export const ADD_SUBJECT_RESPONSE = 'ADD_SUBJECT_RESPONSE';
export const ADD_SUBJECT_FAILED = 'ADD_SUBJECT_FAILED';

export const ENABLE_ASSIGN_SUBJECT_LOADER = 'ENABLE_ASSIGN_SUBJECT_LOADER';
export const DISABLE_ASSIGN_SUBJECT_LOADER = 'DISABLE_ASSIGN_SUBJECT_LOADER';

export const ASSIGN_SUBJECT_REQUEST = 'ASSIGN_SUBJECT_REQUEST';
export const ASSIGN_SUBJECT_RESPONSE = 'ASSIGN_SUBJECT_RESPONSE';
export const ASSIGN_SUBJECT_FAILED = 'ASSIGN_SUBJECT_FAILED';

export const GET_COURSE_BATCH_SUBJECT_REQUEST =
  'GET_COURSE_BATCH_SUBJECT_REQUEST';
export const GET_COURSE_BATCH_SUBJECT_RESPONSE =
  'GET_COURSE_BATCH_SUBJECT_RESPONSE';
export const GET_COURSE_BATCH_SUBJECT_FAILED =
  'GET_COURSE_BATCH_SUBJECT_FAILED';

export const GET_ALL_SUBJECTS_REQUEST = 'GET_ALL_SUBJECTS_REQUEST';
export const GET_ALL_SUBJECTS_RESPONSE = 'GET_ALL_SUBJECTS_RESPONSE';
export const GET_ALL_SUBJECTS_FAILED = 'GET_ALL_SUBJECTS_FAILED';
