export const ADD_DEPARTMENT_REQUEST = 'ADD_DEPARTMENT_REQUEST';
export const ADD_DEPARTMENT_RESPONSE = 'ADD_DEPARTMENT_RESPONSE';
export const ADD_DEPARTMENT_FAILED = 'ADD_DEPARTMENT_FAILED';

export const GET_DEPARTMENT_REQUEST = 'GET_DEPARTMENT_REQUEST';
export const GET_DEPARTMENT_RESPONSE = 'GET_DEPARTMENT_RESPONSE';
export const GET_DEPARTMENT_FAILED = 'GET_DEPARTMENT_FAILED';

export const ENABLE_ADD_DEPARTMENT_LOADER = 'ENABLE_ADD_DEPARTMENT_LOADER';
export const DISABLE_ADD_DEPARTMENT_LOADER = 'DISABLE_ADD_DEPARTMENT_LOADER';
