export const ENABLE_ADD_TIMETABLE_LOADER = 'ENABLE_ADD_TIMETABLE_LOADER';
export const DISABLE_ADD_TIMETABLE_LOADER = 'DISABLE_ADD_TIMETABLE_LOADER';

export const ADD_TIMETABLE_REQUEST = 'ADD_TIMETABLE_REQUEST';
export const ADD_TIMETABLE_RESPONSE = 'ADD_TIMETABLE_RESPONSE';
export const ADD_TIMETABLE_FAILED = 'ADD_TIMETABLE_FAILED';


