export const ENABLE_ADD_CLASS_TEACHER_LOADER =
  'ENABLE_ADD_CLASS_TEACHER_LOADER';
export const DISABLE_ADD_CLASS_TEACHER_LOADER =
  'DISABLE_ADD_CLASS_TEACHER_LOADER';
export const ENABLE_GET_CLASS_TEACHER_LOADER =
  'ENABLE_GET_CLASS_TEACHER_LOADER';
export const DISABLE_GET_CLASS_TEACHER_LOADER =
  'DISABLE_GET_CLASS_TEACHER_LOADER';

export const ADD_CLASS_TEACHER_REQUEST = 'ADD_CLASS_TEACHER_REQUEST';
export const ADD_CLASS_TEACHER_RESPONSE = 'ADD_CLASS_TEACHER_RESPONSE';
export const ADD_CLASS_TEACHER_FAILED = 'ADD_CLASS_TEACHER_FAILED';

export const GET_CLASS_TEACHER_REQUEST = 'GET_CLASS_TEACHER_REQUEST';
export const GET_CLASS_TEACHER_RESPONSE = 'GET_CLASS_TEACHER_RESPONSE';
export const GET_CLASS_TEACHER_FAILED = 'GET_COURSE_FAILED';
