export const ENABLE_ADD_COURSE_LOADER = 'ENABLE_ADD_COURSE_LOADER';
export const DISABLE_ADD_COURSE_LOADER = 'DISABLE_ADD_COURSE_LOADER';
export const ENABLE_GET_COURSE_LOADER = 'ENABLE_GET_COURSE_LOADER';
export const DISABLE_GET_COURSE_LOADER = 'DISABLE_GET_COURSE_LOADER';

export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
export const ADD_COURSE_RESPONSE = 'ADD_COURSE_RESPONSE';
export const ADD_COURSE_FAILED = 'ADD_COURSE_FAILED';

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_RESPONSE = 'GET_COURSE_RESPONSE';
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED';
