export const ADD_USER_TYPE_REQUEST = 'ADD_USER_TYPE_REQUEST';
export const ADD_USER_TYPE_RESPONSE = 'ADD_USER_TYPE_RESPONSE';
export const ADD_USER_TYPE_FAILED = 'ADD_USER_TYPE_FAILED';

export const GET_USER_TYPE_REQUEST = 'GET_USER_TYPE_REQUEST';
export const GET_USER_TYPE_RESPONSE = 'GET_USER_TYPE_RESPONSE';
export const GET_USER_TYPE_FAILED = 'GET_USER_TYPE_FAILED';

export const ENABLE_ADD_USER_TYPE_LOADER = 'ENABLE_ADD_USER_TYPE_LOADER';
export const DISABLE_ADD_USER_TYPE_LOADER = 'DISABLE_ADD_USER_TYPE_LOADER';
