export const ENABLE_GET_INSTITUTION_LOADER = 'ENABLE_GET_INSTITUTION_LOADER';
export const DISABLE_GET_INSTITUTION_LOADER = 'DISABLE_GET_INSTITUTION_LOADER';
export const ENABLE_ADD_INSTITUTION_LOADER = 'ENABLE_ADD_INSTITUTION_LOADER';
export const DISABLE_ADD_INSTITUTION_LOADER = 'DISABLE_ADD_INSTITUTION_LOADER';

export const GET_INSTITUTION_REQUEST = 'GET_INSTITUTION_REQUEST';
export const GET_INSTITUTION_RESPONSE = 'GET_INSTITUTION_RESPONSE';
export const GET_INSTITUTION_FAILED = 'GET_INSTITUTION_FAILED';

export const ADD_INSTITUTION_REQUEST = 'ADD_INSTITUTION_REQUEST';
export const ADD_INSTITUTION_RESPONSE = 'ADD_INSTITUTION_RESPONSE';
export const ADD_INSTITUTION_FAILED = 'ADD_INSTITUTION_FAILED';
