export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_RESPONSE = 'ADD_TASK_RESPONSE';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const GET_TASK_REQUEST = 'GET_TASK_REQUEST';
export const GET_TASK_RESPONSE = 'GET_TASK_RESPONSE';
export const GET_TASK_FAILED = 'GET_TASK_FAILED';

export const ENABLE_ADD_TASK_LOADER = 'ENABLE_ADD_TASK_LOADER';
export const DISABLE_ADD_TASK_LOADER = 'DISABLE_ADD_TASK_LOADER';
