export const ENABLE_ADD_ASSIGNMENTS_LOADER = 'ENABLE_ADD_ASSIGNMENTS_LOADER';
export const DISABLE_ADD_ASSIGNMENTS_LOADER = 'DISABLE_ADD_ASSIGNMENTS_LOADER';

export const GET_ASSIGNMENTS_REQUEST = 'GET_ASSIGNMENTS_REQUEST';
export const GET_ASSIGNMENTS_RESPONSE = 'GET_ASSIGNMENTS_RESPONSE';
export const GET_ASSIGNMENTS_FAILED = 'GET_ASSIGNMENTS_FAILED';

export const ADD_ASSIGNMENTS_REQUEST = 'ADD_ASSIGNMENTS_REQUEST';
export const ADD_ASSIGNMENTS_RESPONSE = 'ADD_ASSIGNMENTS_RESPONSE';
export const ADD_ASSIGNMENTS_FAILED = 'ADD_ASSIGNMENTS_FAILED';
