export const ENABLE_ADD_EMPLOYEE_LOADER = 'ENABLE_ADD_EMPLOYEE_LOADER';
export const DISABLE_ADD_EMPLOYEE_LOADER = 'DISABLE_ADD_EMPLOYEE_LOADER';

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_RESPONSE = 'ADD_EMPLOYEE_RESPONSE';
export const ADD_EMPLOYEE_FAILED = 'ADD_EMPLOYEE_FAILED';
