export const ENABLE_ADD_EMPLOYEE_LOADER = 'ENABLE_ADD_EMPLOYEE_LOADER';
export const DISABLE_ADD_EMPLOYEE_LOADER = 'DISABLE_ADD_EMPLOYEE_LOADER';

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_RESPONSE = 'ADD_EMPLOYEE_RESPONSE';
export const ADD_EMPLOYEE_FAILED = 'ADD_EMPLOYEE_FAILED';

export const GET_EMPLOYEE_BY_DEPARTMENTS_REQUEST =
  'GET_EMPLOYEE_BY_DEPARTMENTS_REQUEST';
export const GET_EMPLOYEE_BY_DEPARTMENTS_RESPONSE =
  'GET_EMPLOYEE_BY_DEPARTMENTS_RESPONSE';
export const GET_EMPLOYEE_BY_DEPARTMENTS_FAILED =
  'GET_EMPLOYEE_BY_DEPARTMENTS_FAILED';

export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_RESPONSE = 'GET_EMPLOYEES_RESPONSE';
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED';
