export const ENABLE_GET_ACADEMIC_LOADER = 'ENABLE_GET_ACADEMIC_LOADER';
export const DISABLE_GET_ACADEMIC_LOADER = 'DISABLE_GET_ACADEMIC_LOADER';
export const ENABLE_ADD_ACADEMIC_LOADER = 'ENABLE_ADD_ACADEMIC_LOADER';
export const DISABLE_ADD_ACADEMIC_LOADER = 'DISABLE_ADD_ACADEMIC_LOADER';

export const GET_ACADEMIC_REQUEST = 'GET_ACADEMIC_REQUEST';
export const GET_ACADEMIC_RESPONSE = 'GET_ACADEMIC_RESPONSE';
export const GET_ACADEMIC_FAILED = 'GET_ACADEMIC_FAILED';

export const ADD_ACADEMIC_REQUEST = 'ADD_ACADEMIC_REQUEST';
export const ADD_ACADEMIC_RESPONSE = 'ADD_ACADEMIC_RESPONSE';
export const ADD_ACADEMIC_FAILED = 'ADD_ACADEMIC_FAILED';
