export const ENABLE_ADD_NOTE_LOADER = 'ENABLE_ADD_NOTE_LOADER';
export const DISABLE_ADD_NOTE_LOADER = 'DISABLE_ADD_NOTE_LOADER';

export const GET_NOTE_REQUEST = 'GET_NOTE_REQUEST';
export const GET_NOTE_RESPONSE = 'GET_NOTE_RESPONSE';
export const GET_NOTE_FAILED = 'GET_NOTE_FAILED';

export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
export const ADD_NOTE_RESPONSE = 'ADD_NOTE_RESPONSE';
export const ADD_NOTE_FAILED = 'ADD_NOTE_FAILED';
