// Pages
import {
  // AppBar,
  // Autocomplete,
  // Avatars,
  // BackendError,
  // Badges,
  // Blank,
  // ButtonNavigation,
  // Buttons,
  // Calendar,
  // Cards,
  // Charts,
  // Chat,
  // Chips,
  // Detail,
  // Dialogs,
  // Dividers,
  // Drawers,
  // Editor,
  // ExpansionPanels,
  // Google,
  // GridList,
  Home,
  // Invoice,
  // Leaflet,
  // Lists,
  // Lockscreen,
  // Media,
  // Menus,
  // Messages,
  // NotFound,
  // Paper,
  // PasswordReset,
  // Pickers,
  // PricingPage,
  // Products,
  // Progress,
  // SelectionControls,
  // Selects,
  // Signin,
  // Signup,
  // Snackbars,
  // Social,
  // Steppers,
  // Tables,
  // Tabs,
  // Taskboard,
  // TextFields,
  // TimelinePage,
  // Tooltips,
  // Widgets,
  //Settings
  InstitutionDetails,
  AcademicDetails,
  StudentImport,
  EmployeeImport,
  Privileges,
  AssignCourse,
  Users,
  ApplicantList,
  LoginPage,
  FeesAllocationImport,
  CasteAndReligion,
  VisitorsList,
  Course,
  Batch,
  ClassTeacherAllocation,
  Subjects,
  AssignSubject,
  SubjectAllocation,
  ElectiveSubject,
  SubjectAllocationImport,
  LessonPlanning,
  SetTimetable,
  ActiveTimeTable,
  ViewBatchTimeTable,
  ViewTeacherTimetable,
  TeacherWorkingHours,
  TimetableExport,
  TimetableImport,
  SetTerm,
  GPASkill,
  GPASkillMark,
  SetSubjectCreditPoint,
  CreateExam,
  SetGradeScale,
  SetAssessment,
  SearchProxy,
  AddAssignments,
  AddNotes,
  AssignmentsImport,
  NewOnlineExam,
  ViewOnlineExam,
  ViewExamResults,
  AssignTask,
  TaskDetails,
  VideoUpload,
  CertificateType,
  CustomCertificate,
  GenerateCertificate,
  PlacementsCellMembers,
  PlacementVendor,
  PlacementAttendees,
  PlacedDetails,
  OccurrenceRegister,
  Circular,
  AddUserType,
  AddDepartment,
  AddDesignation,
  AddEmployee,
  EmployeeList,
  AddBankDetails,
  PrintList,
  Withdrawal,
  PayHead,
  PayableType,
  SalarySettings,
  EmployeeSalary,
  GeneratepaySlip,
  LeaveCategory,
  LeaveDetails,
  LeaveApplication,
  LeaveApproval,
  Attendance,
  StudentCategory,
  StudentList,
  StudentAttendance,
  StudentPrintList,
  GuardianList,
  RollNumber,
  StudentAttendanceImport,
  FeeCategory,
  FeeSubCategory,
  FeeWaiver,
  FeeTemplate,
  FeeAllocation,
  QuickPayment,
  Reports,
  FeeImport,
  AccountGroup,
  VoucherHead,
  CreateVoucher,
  DayBook,
  CashBook,
  BankBook,
  AddCategory,
  AddBooks,
  RequestDetails,
  BookReturn,
  LibraryReports,
  LibraryImport,
  AddVehicle,
  AddDriver,
  AddRoute,
  AddDestination,
  TransportAllocation,
  TransportImport,
  TransportSMSAlert,
  DataExport,
  AddEvent,
  EventTypes,
  HostelDetails,
  HostelRoom,
  HostelAllocation,
  HostelRequestDetails,
  HostelTransfer,
  HostelRegister,
  HostelVisitor,
  HostelFeeCollection,
  Vendors,
  InventoryCategory,
  InventoryItem,
  StockRegister,
  IssuedReport,
  StudentPerformance,
  StudentReport,
  StudentDetailsReport,
  FeeDue,
  FeePaid,
  ElectiveReports,
  Absentees,
  ClassReport,
  FeesConsoliadatedReport,
  VisitorSMSSettings,
  BulkSms,
  EmailSettings,
  CreateTemplate,
  SendEmail,
} from './pages';

import HomeIcon from '@material-ui/icons/Home';
import SettingsIcon from '@material-ui/icons/Settings';
import PeopleAlt from '@material-ui/icons/PeopleAlt';
import WorkIcon from '@material-ui/icons/Work';
import RemoveRedEyeIcon from '@material-ui/icons/RemoveRedEye';
import PersonIcon from '@material-ui/icons/Person';
import FinanceIcon from '@material-ui/icons/CreditCard';
import LibraryIcon from '@material-ui/icons/ImportContacts';
import TransportIcon from '@material-ui/icons/DriveEta';
import DataExportIcon from '@material-ui/icons/CloudDownload';
import EventIcon from '@material-ui/icons/Star';
import HostelIcon from '@material-ui/icons/HomeWork';
import StoreIcon from '@material-ui/icons/FormatListBulleted';
import TrendingUpIcon from '@material-ui/icons/TrendingUp';
import ReportIcon from '@material-ui/icons/FileCopy';
import EmailIcon from '@material-ui/icons/Email';

export default {
  items: [
    {
      path: '/',
      name: 'Dashboard',
      type: 'link',
      icon: HomeIcon,
      component: Home,
      roles: ['admin', 'student', 'teacher', 'guardian', 'superadmin'],
    },
    {
      path: '/settings',
      name: 'Settings',
      type: 'submenu',
      icon: SettingsIcon,
      roles: ['admin', 'superadmin'],
      // badge: {
      //   type: 'primary',
      //   value: '5',
      // },
      children: [
        {
          path: '/institution',
          name: 'Institution Details',
          component: InstitutionDetails,
        },
        {
          path: '/academic',
          name: 'Academic Details',
          component: AcademicDetails,
        },
        {
          path: '/student',
          name: 'Student Import',
          component: StudentImport,
        },
        {
          path: '/employee',
          name: 'Employee Import',
          component: EmployeeImport,
        },
        {
          path: '/privileges',
          name: 'Privileges',
          component: Privileges,
        },
        {
          path: '/assign',
          name: 'Assign Course',
          component: AssignCourse,
        },
        {
          path: '/users',
          name: 'Users',
          component: Users,
        },
        {
          path: '/applicant',
          name: 'Applicant List',
          component: ApplicantList,
        },
        {
          path: '/loginform',
          name: 'Login Page',
          component: LoginPage,
        },
        {
          path: '/feesallocation',
          name: 'Fees Allocation Import',
          component: FeesAllocationImport,
        },
        {
          path: '/caste',
          name: 'Caste And Religion',
          component: CasteAndReligion,
        },
        {
          path: '/visitors',
          name: 'Visitors List',
          component: VisitorsList,
        },
      ],
    },
    {
      path: '/academic',
      name: 'Academic',
      icon: PeopleAlt,
      type: 'twomenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/coursebatch',
          name: 'Course & Batch',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/course',
              name: 'Course',
              component: Course,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/batch',
              name: 'Batch',
              component: Batch,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/allocation',
              name: 'Class Teacher Aallocation',
              component: ClassTeacherAllocation,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/subjects',
          name: 'Subjects',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/subjects',
              name: 'Subjects',
              component: Subjects,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/assign',
              name: 'Assign Subject',
              component: AssignSubject,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/allocation',
              name: 'Subject Allocation',
              component: SubjectAllocation,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/elective',
              name: 'Elective Subject',
              component: ElectiveSubject,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/allocationimport',
              name: 'Subject Allocation Import',
              component: SubjectAllocationImport,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/lessonplanning',
          name: 'Lesson Planning',
          type: 'submenu',
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
          children: [
            {
              path: '/planning',
              name: 'Lesson Planning',
              component: LessonPlanning,
              roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
            },
          ],
        },
        {
          path: '/timetable',
          name: 'Timetable',
          type: 'submenu',
          roles: ['admin', 'teacher', 'superadmin'],
          children: [
            {
              path: '/set',
              name: 'Set Timetable',
              component: SetTimetable,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/active',
              name: 'Active Timetable',
              component: ActiveTimeTable,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/batch',
              name: 'View Batch Timetable',
              component: ViewBatchTimeTable,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/teacher',
              name: 'View Teacher Timetable',
              component: ViewTeacherTimetable,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/proxy',
              name: 'Search Proxy',
              component: SearchProxy,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/export',
              name: 'Timetable Export',
              component: TimetableExport,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/import',
              name: 'Timetable Import',
              component: TimetableImport,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/working',
              name: 'Teacher Working Hours',
              component: TeacherWorkingHours,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/exams',
          name: 'Exams',
          type: 'submenu',
          roles: ['admin', 'guardian', 'superadmin'],
          children: [
            {
              path: '/set',
              name: 'Set Term',
              component: SetTerm,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/create',
              name: 'Create Exam',
              component: CreateExam,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/skill',
              name: 'GPA Skill',
              component: GPASkill,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/skillmark',
              name: 'GPA Skill Mark',
              component: GPASkillMark,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/gradescale',
              name: 'Set Grade Scale',
              component: SetGradeScale,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/subject',
              name: 'Subject Credit Point',
              component: SetSubjectCreditPoint,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/assessment',
              name: 'Set Assessment',
              component: SetAssessment,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/onlineexams',
          name: 'Online Exam',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/new',
              name: 'New Online Exam',
              component: NewOnlineExam,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/unit',
              name: 'Unit Test',
              component: CreateExam,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/video',
              name: 'Video Upload',
              component: VideoUpload,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/view',
              name: 'View Exam Results',
              component: ViewExamResults,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/online',
              name: 'View Online Exam',
              component: ViewOnlineExam,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/assignment',
          name: 'Assignments And Notes',
          type: 'submenu',
          roles: ['admin', 'teacher', 'superadmin'],
          children: [
            {
              path: '/add',
              name: 'Add Assignment',
              component: AddAssignments,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/notes',
              name: 'Add Notes',
              component: AddNotes,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/import',
              name: 'Assignments Import',
              component: AssignmentsImport,
              roles: ['admin', 'teacher', 'superadmin'],
            },
          ],
        },
        {
          path: '/certificate',
          name: 'Certificate',
          type: 'submenu',
          roles: ['admin', 'teacher', 'superadmin'],
          children: [
            {
              path: '/type',
              name: 'Certificate Type',
              component: CertificateType,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/custom',
              name: 'Custom Certificate',
              component: CustomCertificate,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/generate',
              name: 'Generate Certificate',
              component: GenerateCertificate,
              roles: ['admin', 'teacher', 'superadmin'],
            },
          ],
        },
        {
          path: '/placements',
          name: 'Placements',
          type: 'submenu',
          roles: ['admin', 'teacher', 'superadmin'],
          children: [
            {
              path: '/placements',
              name: 'Placements',
              component: PlacementsCellMembers,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/vendor',
              name: 'Placement Vendor',
              component: PlacementVendor,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/attendees',
              name: 'Attendees',
              component: PlacementAttendees,
              roles: ['admin', 'teacher', 'superadmin'],
            },
            {
              path: '/details',
              name: 'Placed Details',
              component: PlacedDetails,
              roles: ['admin', 'teacher', 'superadmin'],
            },
          ],
        },
        {
          path: '/occurrence',
          name: 'Occurrence',
          type: 'submenu',
          roles: ['admin', 'teacher', 'superadmin'],
          children: [
            {
              path: '/occurrence',
              name: 'Occurrence Register',
              component: OccurrenceRegister,
              roles: ['admin', 'teacher', 'superadmin'],
            },
          ],
        },
        {
          path: '/circular',
          name: 'Circular',
          type: 'submenu',
          roles: ['admin', 'teacher', 'superadmin'],
          children: [
            {
              path: '/circular',
              name: 'Circular',
              component: Circular,
              roles: ['admin', 'teacher', 'superadmin'],
            },
          ],
        },
        {
          path: '/result',
          name: 'Results',
          type: 'submenu',
          roles: ['student', 'superadmin'],
          component: ViewExamResults,
          children: [
            {
              path: '/results',
              name: 'Results',
              roles: ['student', 'superadmin'],
            },
          ],
        },
      ],
    },
    {
      path: '/hr',
      name: 'HR/Payroll',
      icon: RemoveRedEyeIcon,
      type: 'twomenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/employee',
          name: 'Employee Management',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/course',
              name: 'Add User Type',
              component: AddUserType,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/department',
              name: 'Add Department',
              component: AddDepartment,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/designation',
              name: 'Add Designation',
              component: AddDesignation,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/employee',
              name: 'Add Employee',
              component: AddEmployee,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/list',
              name: 'Employee List',
              component: EmployeeList,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/bank',
              name: 'Add Bank Details',
              component: AddBankDetails,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/print',
              name: 'Print List',
              component: PrintList,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/withdrawal',
              name: 'Withdrawal',
              component: Withdrawal,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/payroll',
          name: 'PayRoll',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/payhead',
              name: 'PayHead',
              component: PayHead,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/types',
              name: 'Payment Types',
              component: PayableType,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/salary',
              name: 'Salary Settings',
              component: SalarySettings,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/salary',
              name: 'Employee Salary',
              component: EmployeeSalary,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/generate',
              name: 'Generate Pay slip',
              component: GeneratepaySlip,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/leave',
          name: 'Leave Management',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/category',
              name: 'Leave Category',
              component: LeaveCategory,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/details',
              name: 'Leave Details',
              component: LeaveDetails,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/application',
              name: 'Leave Application',
              component: LeaveApplication,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/approval',
              name: 'Leave Approval',
              component: LeaveApproval,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/attendance',
          name: 'Attendance',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/attendance',
              name: 'Attendance',
              component: Attendance,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
      ],
    },
    {
      path: '/student',
      name: 'Student',
      icon: PersonIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/category',
          name: 'Student Category',
          component: StudentCategory,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/list',
          name: 'Student List',
          component: StudentList,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/attendance',
          name: 'Attendance',
          component: StudentAttendance,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/print',
          name: 'Print List',
          component: StudentPrintList,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/guardian',
          name: 'Guardian List',
          component: GuardianList,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/rollnumber',
          name: 'Roll Number',
          component: RollNumber,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/import',
          name: 'Student Attendance Import',
          component: StudentAttendanceImport,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/finance',
      name: 'Finance',
      icon: FinanceIcon,
      type: 'twomenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/fee',
          name: 'Fees',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/category',
              name: 'Fee Category',
              component: FeeCategory,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/subcategory',
              name: 'Fee SubCategory',
              component: FeeSubCategory,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/waiver',
              name: 'Fee Waiver',
              component: FeeWaiver,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/template',
              name: 'Fee Template',
              component: FeeTemplate,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/allocation',
              name: 'Fee Allocation',
              component: FeeAllocation,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/payment',
              name: 'Quick Payment',
              component: QuickPayment,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/reports',
              name: 'Reports',
              component: Reports,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/import',
              name: 'Fee Import',
              component: FeeImport,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/accounting',
          name: 'Accounting',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/group',
              name: 'Account Group',
              component: AccountGroup,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/voucher',
              name: 'Voucher Head',
              component: VoucherHead,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/create',
              name: 'Create Voucher',
              component: CreateVoucher,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/daybook',
              name: 'Day Book',
              component: DayBook,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/cashbook',
              name: 'Cash Book',
              component: CashBook,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/bankbook',
              name: 'Bank Book',
              component: BankBook,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
      ],
    },
    {
      path: '/library',
      name: 'Library',
      icon: LibraryIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/category',
          name: 'Add Category',
          component: AddCategory,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/books',
          name: 'Add Books',
          component: AddBooks,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/request',
          name: 'Request Details',
          component: RequestDetails,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/return',
          name: 'Book Return',
          component: BookReturn,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/reports',
          name: 'Reports',
          component: LibraryReports,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/import',
          name: 'Import',
          component: LibraryImport,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/transport',
      name: 'Transport',
      icon: TransportIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/vehicle',
          name: 'Add Vehicle',
          component: AddVehicle,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/driver',
          name: 'Add Driver',
          component: AddDriver,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/route',
          name: 'Add Route',
          component: AddRoute,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/destination',
          name: 'Add Destination',
          component: AddDestination,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/allocation',
          name: 'Transport Allocation',
          component: TransportAllocation,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/import',
          name: 'Import',
          component: TransportImport,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/sms',
          name: 'SMS Alert',
          component: TransportSMSAlert,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/hostel',
      name: 'Hostel',
      icon: HostelIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/details',
          name: 'Hostel Details',
          component: HostelDetails,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/room',
          name: 'Hostel Room',
          component: HostelRoom,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/allocation',
          name: 'Hostel Allocation',
          component: HostelAllocation,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/request',
          name: 'Request Details',
          component: HostelRequestDetails,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/transfer',
          name: 'Hostel Transfer/Vacate',
          component: HostelTransfer,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/register',
          name: 'Hostel Register',
          component: HostelRegister,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/visitor',
          name: 'Hostel Visitor',
          component: HostelVisitor,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/fee',
          name: 'Hostel Fee Collection',
          component: HostelFeeCollection,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/store',
      name: 'Store Management',
      icon: StoreIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/vendor',
          name: 'Vendors',
          component: Vendors,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/category',
          name: 'Inventory Category',
          component: InventoryCategory,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/item',
          name: 'Inventory Item',
          component: InventoryItem,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/stock',
          name: 'Stock Register',
          component: StockRegister,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/issued',
          name: 'Issued Report',
          component: IssuedReport,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/performance',
      name: 'Performance',
      icon: TrendingUpIcon,
      type: 'twomenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/gpa',
          name: 'GPA',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/performance',
              name: 'Student Performance',
              component: StudentPerformance,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/course',
              name: 'Course Performance',
              component: Batch,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
        {
          path: '/cce',
          name: 'CCE',
          type: 'submenu',
          roles: ['admin', 'superadmin'],
          children: [
            {
              path: '/performance',
              name: 'Student Performance',
              component: Course,
              roles: ['admin', 'superadmin'],
            },
            {
              path: '/course',
              name: 'Course Performance',
              component: Batch,
              roles: ['admin', 'superadmin'],
            },
          ],
        },
      ],
    },
    {
      path: '/task',
      name: 'Data Export',
      icon: DataExportIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/data',
          name: 'Data Export',
          component: DataExport,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/event',
      name: 'Event',
      icon: EventIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/event',
          name: 'Event Types',
          component: EventTypes,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/add',
          name: 'Add Events',
          component: AddEvent,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/message',
      name: 'Messages/SMS',
      icon: EmailIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/visitor',
          name: 'Visitor SMS Settings',
          component: VisitorSMSSettings,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/bulk',
          name: 'Bulk SMS',
          component: BulkSms,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/settings',
          name: 'Email Settings',
          component: EmailSettings,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/template',
          name: 'Create Template',
          component: CreateTemplate,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/send',
          name: 'Send Email',
          component: SendEmail,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
      ],
    },
    {
      path: '/task',
      name: 'Task Manager',
      icon: WorkIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/assign',
          name: 'Assign Task',
          component: AssignTask,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/details',
          name: 'Task Details',
          component: TaskDetails,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
      ],
    },
    {
      path: '/report',
      name: 'Reports',
      icon: ReportIcon,
      type: 'submenu',
      roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
      children: [
        {
          path: '/student',
          name: 'Student Reports',
          component: StudentReport,
          roles: ['student', 'admin', 'teacher', 'superadmin'],
        },
        {
          path: '/details',
          name: 'Student Details',
          component: StudentDetailsReport,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
        {
          path: '/due',
          name: 'Fee Due',
          component: FeeDue,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
        {
          path: '/paid',
          name: 'Fee Paid',
          component: FeePaid,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
        {
          path: '/elective',
          name: 'Elective Reports',
          component: ElectiveReports,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
        {
          path: '/absentees',
          name: 'Absentees',
          component: Absentees,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
        {
          path: '/class',
          name: 'Class Report',
          component: ClassReport,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
        {
          path: '/consolidated',
          name: 'Fees Consolidate Report',
          component: FeesConsoliadatedReport,
          roles: ['student', 'admin', 'teacher', 'guardian', 'superadmin'],
        },
      ],
    },

    // {
    //   path: '/widgets',
    //   name: 'Widgets',
    //   type: 'link',
    //   icon: PhotoIcon,
    //   component: Widgets,
    // },
    // {
    //   path: '/material',
    //   name: 'Material',
    //   type: 'submenu',
    //   icon: EqualizerIcon,
    //   badge: {
    //     type: 'error',
    //     value: '10',
    //   },
    //   children: [
    //     {
    //       path: '/appbar',
    //       name: 'App Bar',
    //       component: AppBar,
    //     },
    //     {
    //       path: '/autocomplete',
    //       name: 'Auto Complete',
    //       component: Autocomplete,
    //     },
    //     {
    //       path: '/avatars',
    //       name: 'Avatars',
    //       component: Avatars,
    //     },
    //     {
    //       path: '/badges',
    //       name: 'Badges',
    //       component: Badges,
    //     },
    //     {
    //       path: '/button-navigation',
    //       name: 'Button Navigation',
    //       component: ButtonNavigation,
    //     },
    //     {
    //       path: '/buttons',
    //       name: 'Buttons',
    //       component: Buttons,
    //     },
    //     {
    //       path: '/cards',
    //       name: 'Cards',
    //       component: Cards,
    //     },
    //     {
    //       path: '/chips',
    //       name: 'Chips',
    //       component: Chips,
    //     },
    //     {
    //       path: '/dialogs',
    //       name: 'Dialogs',
    //       component: Dialogs,
    //     },
    //     {
    //       path: '/dividers',
    //       name: 'Dividers',
    //       component: Dividers,
    //     },
    //     {
    //       path: '/drawers',
    //       name: 'Drawers',
    //       component: Drawers,
    //     },
    //     {
    //       path: '/expansion-panels',
    //       name: 'Expansion Panels',
    //       component: ExpansionPanels,
    //     },
    //     {
    //       path: '/grid-list',
    //       name: 'Grid List',
    //       component: GridList,
    //     },
    //     {
    //       path: '/lists',
    //       name: 'Lists',
    //       component: Lists,
    //     },
    //     {
    //       path: '/menus',
    //       name: 'Menus',
    //       component: Menus,
    //     },
    //     {
    //       path: '/paper',
    //       name: 'Paper',
    //       component: Paper,
    //     },
    //     {
    //       path: '/pickers',
    //       name: 'Pickers',
    //       component: Pickers,
    //     },
    //     {
    //       path: '/progress',
    //       name: 'Progress',
    //       component: Progress,
    //     },
    //     {
    //       path: '/selection-controls',
    //       name: 'Selection Controls',
    //       component: SelectionControls,
    //     },
    //     {
    //       path: '/selects',
    //       name: 'Selects',
    //       component: Selects,
    //     },
    //     {
    //       path: '/snackbars',
    //       name: 'Snackbars',
    //       component: Snackbars,
    //     },
    //     {
    //       path: '/steppers',
    //       name: 'Steppers',
    //       component: Steppers,
    //     },
    //     {
    //       path: '/tables',
    //       name: 'Tables',
    //       component: Tables,
    //     },
    //     {
    //       path: '/tabs',
    //       name: 'Tabs',
    //       component: Tabs,
    //     },
    //     {
    //       path: '/text-fields',
    //       name: 'Text Fields',
    //       component: TextFields,
    //     },
    //     {
    //       path: '/tooltips',
    //       name: 'Tooltips',
    //       component: Tooltips,
    //     },
    //   ],
    // },
    // {
    //   path: '/editor',
    //   name: 'Editor',
    //   type: 'link',
    //   icon: Looks3Icon,
    //   component: Editor,
    // },
    // {
    //   path: '/ecommerce',
    //   name: 'Ecommerce',
    //   type: 'submenu',
    //   icon: Looks4Icon,
    //   badge: {
    //     type: 'secondary',
    //     value: 'N',
    //   },
    //   children: [
    //     {
    //       path: '/products',
    //       name: 'Products',
    //       component: Products,
    //     },
    //     {
    //       path: '/detail',
    //       name: 'Detail',
    //       component: Detail,
    //     },
    //   ],
    // },
    // {
    //   path: '/taskboard',
    //   name: 'Taskboard',
    //   type: 'link',
    //   icon: ViewColumnIcon,
    //   component: Taskboard,
    // },
    // {
    //   path: '/charts',
    //   name: 'Charts',
    //   type: 'link',
    //   icon: ShowChartIcon,
    //   component: Charts,
    // },
    // {
    //   path: '/maps',
    //   name: 'Maps',
    //   type: 'submenu',
    //   icon: NavigationIcon,
    //   children: [
    //     {
    //       path: '/google',
    //       name: 'Google',
    //       component: Google,
    //     },
    //     {
    //       path: '/leaflet',
    //       name: 'Leaflet',
    //       component: Leaflet,
    //     },
    //   ],
    // },
    // {
    //   path: '/pages',
    //   name: 'Pages',
    //   type: 'submenu',
    //   icon: PagesIcon,
    //   children: [
    //     {
    //       path: '/invoice',
    //       name: 'Invoice',
    //       component: Invoice,
    //     },
    //     {
    //       path: '/timeline',
    //       name: 'Timeline',
    //       component: TimelinePage,
    //     },
    //     {
    //       path: '/blank',
    //       name: 'Blank',
    //       component: Blank,
    //     },
    //     {
    //       path: '/pricing',
    //       name: 'Pricing',
    //       component: PricingPage,
    //     },
    //   ],
    // },
    // {
    //   name: 'Authentication',
    //   type: 'submenu',
    //   icon: PersonIcon,
    //   children: [
    //     {
    //       path: '/signin',
    //       name: 'Signin',
    //       component: Signin,
    //     },
    //     {
    //       path: '/signup',
    //       name: 'Signup',
    //       component: Signup,
    //     },
    //     {
    //       path: '/forgot',
    //       name: 'Forgot',
    //       component: PasswordReset,
    //     },
    //     {
    //       path: '/lockscreen',
    //       name: 'Lockscreen',
    //       component: Lockscreen,
    //     },
    //   ],
    // },
    // {
    //   name: 'Error',
    //   type: 'submenu',
    //   icon: FaceIcon,
    //   children: [
    //     {
    //       path: '/404',
    //       name: '404',
    //       component: NotFound,
    //     },
    //     {
    //       path: '/500',
    //       name: 'Error',
    //       component: BackendError,
    //     },
    //   ],
    // },
    // {
    //   path: 'https://iamnyasha.github.io/react-primer-docs/',
    //   name: 'Documentation',
    //   type: 'external',
    //   icon: LocalLibraryIcon,
    // },
    // {
    //   path: 'https://primer.fusepx.com',
    //   name: 'Get Angular Version',
    //   type: 'external',
    //   icon: BookmarkIcon,
    // },
  ],
};
