export const ENABLE_ADD_BATCH_LOADER = 'ENABLE_ADD_BATCH_LOADER';
export const DISABLE_ADD_BATCH_LOADER = 'DISABLE_ADD_BATCH_LOADER';

export const ADD_BATCH_REQUEST = 'ADD_BATCH_REQUEST';
export const ADD_BATCH_RESPONSE = 'ADD_BATCH_RESPONSE';
export const ADD_BATCH_FAILED = 'ADD_BATCH_FAILED';

export const GET_COURSES_BATCH_REQUEST = 'GET_COURSES_BATCH_REQUEST';
export const GET_COURSES_BATCH_RESPONSE = 'GET_COURSES_BATCH_RESPONSE';
export const GET_COURSES_BATCH_FAILED = 'GET_COURSES_BATCH_FAILED';
