export const GET_VISITORS_REQUEST = 'GET_VISITORS_REQUEST';
export const GET_VISITORS_RESPONSE = 'GET_VISITORS_RESPONSE';
export const GET_VISITORS_FAILED = 'GET_VISITORS_FAILED';

export const ADD_VISITORS_REQUEST = 'ADD_VISITORS_REQUEST';
export const ADD_VISITORS_RESPONSE = 'ADD_VISITORS_RESPONSE';
export const ADD_VISITORS_FAILED = 'ADD_VISITORS_FAILED';

export const ENABLE_ADD_VISITORS_LOADER = 'ENABLE_ADD_VISITORS_LOADER';
export const DISABLE_ADD_VISITORS_LOADER = 'DISABLE_ADD_VISITORS_LOADER';
